######### Flask
flask:
  root_path: null
  template_folder: "html/"
  static_folder: "/"
  secret_key: b'W\xac\x81*\x04\xd3\xd4\n\xbf\xb9\t\x18\xd7\xd9%\x9c\xff\xf9\x89 S\x81\xc9_'


######### URL
# Won't be needed in production
URL:
  prefix: "http"
  sub_domain: "www"
  domain_name: "localhost"
  domain_extension: "com"
  port: "5000"


######### Database
# By default database is disabled
# database:
#   enabled: false
#   name: "template"
#   user: "template"
#   password: "password_template"
#   host: "127.0.0.1"
#   port: "33060"
#   charset: "utf8mb4"
#   collate: "utf8mb4_0900_ai_ci"


######### eMail
eMail:
  regEx: "^[a-zA-Z0-9][a-zA-Z0-9._-]{0,20}[a-zA-Z0-9]@[a-z][a-zA-Z0-9-_]{1,20}.[a-z]{2,3}$"
  subject: "X"

  GMail:
    enabled: false
    eMail: null
    password: null

  SendGrid:
    domain: null
    api_key: null


######### Site Defaults
default:
  currency: "USD"
  title: "X"
  language: "en"
  charset: "utf-8"

  # To Control App's State (Offline, Under Development etc.)
  # appIsDown:
  #   reason: "Under Development"
  #   explanation: "Long text that describes the 'reason'"
  #   logo: "SVG Logo To Be Shown"

  # For External Color Configurations
  color:
    brand:
      hue: 230        # deg
      saturation: 13  # %
      lightness: 9    # %


######### Menu
menu:
  enabled: true
  menus:
    - name: "home"
    - name: "signUp"
    - name: "logIn"
    - name: "logOut"
    - name: "demo"
      logo: "laboratory"
    - name: "languagesLibrary"
      logo: "openBook"


######### Pages
pages:
  home:
    enabled: true
    authenticity_statuses:
      - "everyone"

    endpoints:
      - "/"
      - "/home"


  signUp:
    enabled: true
    authenticity_statuses:
      - "unauthenticated"

    endpoints:
      - "/signUp"


  eMailConfirmation:
    enabled: true
    authenticity_statuses:
      - "unauthorized"

    endpoints:
      - "/eMailConfirmation"


  logIn:
    enabled: true
    authenticity_statuses:
      - "unauthenticated"

    endpoints:
      - "/logIn"


  logOut:
    enabled: true
    authenticity_statuses:
      - "unauthorized"
      - "authorized"

    endpoints:
      - "/logOut"


  demo:
    enabled: true
    authenticity_statuses:
      - "everyone"

    endpoints:
      - "/demo"


  languagesLibrary:
    enabled: true
    authenticity_statuses:
      - "everyone"

    endpoints:
      - "/languagesLibrary"


######### Username
username:
  min_length: 6
  max_length: 50
  regEx: "^[a-zA-Z0-9'_-]+$"


######### Password
password:
  min_length: 6
  max_length: 50
  regEx: "^(?=.*[a-z])(?=.*[0-9])(?=.*[-!@#$%^&*_+])[-!@#$%^&*_+A-Za-z0-9]{6,}$"


######### Phone Number
phoneNumber:
  regEx: "^[+]{1,1}[0-9]{11,11}$"


######## Stripe payment
