######### Flask
root_path: null
template_folder: "html/"
static_folder: "/"


######### URL
# Won't be needed in production
URL:
  prefix: "http"
  sub_domain: "www"
  domain_name: "localhost"
  domain_extension: "com"
  port: "8088"


######### HTML
HTML:
  charset: "utf-8"


######### Username
username:
  min_length: 6
  max_length: 50
  regEx: "^[a-zA-Z0-9'_-]+$"


######### Password
password:
  min_length: 6
  max_length: 50
  regEx: "^(?=.*[a-z])(?=.*[0-9])(?=.*[-!@#$%^&*_+])[-!@#$%^&*_+A-Za-z0-9]{6,}$"


######### Phone Number
phoneNumber:
  regEx: "^[+]{1,1}[0-9]{11,11}$"


######### eMail
eMail:
  regEx: "^[a-zA-Z0-9][a-zA-Z0-9._-]{0,20}[a-zA-Z0-9]@[a-z][a-zA-Z0-9-_]{1,20}.[a-z]{2,3}$"


######## Stripe payment
