######### Version
version: "0.101.5"

######### Flask
flask:
  root_path: null
  template_folder: "html/"
  static_folder: "/"


######### URL
# Won't be needed in production
URL:
  prefix: "http"
  sub_domain: "www"
  domain_name: "localhost"
  domain_extension: "com"
  port: "5000"


######### eMail
eMail:
  regEx: "^[a-zA-Z0-9][a-zA-Z0-9._-]{0,20}[a-zA-Z0-9]@[a-z][a-zA-Z0-9-_]{1,20}.[a-z]{2,3}$"
  subject: "X"

  GMail:
    enabled: false
    eMail: null
    password: null

  SendGrid:
    enabled: false
    domain: null
    api_key: null


######### Site Defaults
default:
  language: "en"
  title: "X"
  charset: "utf-8"
  currency: "USD"

  # To Control App's State (Offline, Under Development etc.)
  # appIsDown:
  #   title: "Under Development"
  #   explanation: "Long text that describes the 'title'"
  #   icon: "SVG Logo To Be Shown"

  # For External Color Configurations
  color:
    brand:
      hue: 230        # deg
      saturation: 13  # %
      lightness: 9    # %

  # App Icon Settings
  icon:
    favicon:
      sizes: "32x32"
      type: "image/png"
      dark: "favicon/favicon-32x32-dark.png"
      light: "favicon/favicon-32x32-light.png"

  # Enables All "print"s And "console.log"s
  debug: true


######### Pages
pages:
  home:
    enabled: true
    endpoints:
      - "/"
      - "/home"


  signUp:
    enabled: true
    authenticity_statuses:
      - "unauthenticated"

    endpoints:
      - "/signUp"


  logIn:
    enabled: true
    authenticity_statuses:
      - "unauthenticated"

    endpoints:
      - "/logIn"


  eMailConfirmation:
    enabled: true
    authenticity_statuses:
      - "unauthorized"

    endpoints:
      - "/eMailConfirmation"


  logOut:
    enabled: true
    authenticity_statuses:
      - "unauthorized"
      - "authorized"

    endpoints:
      - "/logOut"


  languagesLibrary:
    enabled: true
    endpoints:
      - "/languagesLibrary"


######### Menu
menu:
  enabled: true
  menus:
    - name: "home"
    - name: "signUp"
    - name: "logIn"
    - name: "logOut"

    - name: "languagesLibrary"
      logo: "openBook"


######### Username
username:
  min_length: 6
  max_length: 50
  regEx: "^[a-zA-Z0-9'_-]+$"


######### Password
password:
  min_length: 6
  max_length: 50
  regEx: "^(?=.*[a-z])(?=.*[0-9])(?=.*[-!@#$%^&*_+])[-!@#$%^&*_+A-Za-z0-9]{6,}$"


######### Phone Number
phoneNumber:
  regEx: "^[+]{1,1}[0-9]{11,11}$"

