######### Flask
flask:
  root_path: null
  template_folder: "html/"
  static_folder: "/"
  secret_key: b'W\xac\x81*\x04\xd3\xd4\n\xbf\xb9\t\x18\xd7\xd9%\x9c\xff\xf9\x89 S\x81\xc9_'


######### URL
# Won't be needed in production
URL:
  prefix: "http"
  sub_domain: "www"
  domain_name: "localhost"
  domain_extension: "com"
  port: "8088"


######### Database
# By default database disabled
# database:
#   enabled: false
#   name: "template"
#   user: "template"
#   password: "password_template"
#   host: "127.0.0.1"
#   port: "33060"
#   charset: "utf8mb4"
#   collate: "utf8mb4_0900_ai_ci"


######### Site Defaults
default:
  currency: "USD"
  title: "X-WebApp"
  language: "en"


######### HTML
HTML:
  charset: "utf-8"


######### Menu
menu:
    enabled: true
    menus:

      home:
        enabled: true

      signUp:
        enabled: true

      logIn:
        enabled: true

      logOut:
        enabled: true

      demo:
        enabled: true


######### Pages
pages:
  home:
    enabled: true
    allowed:
      - "everyone"

    aliases:
      - "/"
      - "/home"


  signUp:
    enabled: true
    allowed:
      - "unauthenticated"

    aliases:
      - "/signUp"


  eMailConfirmation:
    enabled: true
    allowed:
      - "unauthorized"

    aliases:
      - "/eMailConfirmation"


  logIn:
    enabled: true
    allowed:
      - "unauthenticated"

    aliases:
      - "/logIn"


  logOut:
    enabled: true
    allowed:
      - "unauthorized"
      - "authorized"

    aliases:
      - "/logOut"


  demo:
    enabled: true
    allowed:
      - "everyone"

    aliases:
      - "/demo"




######### Username
username:
  min_length: 6
  max_length: 50
  regEx: "^[a-zA-Z0-9'_-]+$"


######### Password
password:
  min_length: 6
  max_length: 50
  regEx: "^(?=.*[a-z])(?=.*[0-9])(?=.*[-!@#$%^&*_+])[-!@#$%^&*_+A-Za-z0-9]{6,}$"


######### Phone Number
phoneNumber:
  regEx: "^[+]{1,1}[0-9]{11,11}$"


######### eMail
eMail:
  regEx: "^[a-zA-Z0-9][a-zA-Z0-9._-]{0,20}[a-zA-Z0-9]@[a-z][a-zA-Z0-9-_]{1,20}.[a-z]{2,3}$"


######## Stripe payment
