######### Version
version: "0.129.0"

######### Flask
flask:
  root_path: null
  template_folder: "html/"
  static_folder: "/"


######### URL
# Won't be needed in production
URL:
  prefix: "http"
  sub_domain: "www"
  domain_name: "localhost"
  domain_extension: "com"
  port: "5000"


######### eMail
eMail:
  regEx: "^[a-zA-Z0-9][a-zA-Z0-9._-]{0,20}[a-zA-Z0-9]@[a-z][a-zA-Z0-9-_]{1,20}.[a-z]{2,3}$"
  subject: "X"

  GMail:
    enabled: false
    eMail: null
    password: null

  SendGrid:
    enabled: false
    domain: null
    api_key: null


######### App Defaults
default:
  title: "x"
  charset: "utf-8"
  currency: "USD"

  # In the initial attempt, the application seeks to retrieve the user's selected language in case of a logged-in session.
  # Subsequently, on the second attempt, it endeavors to retrieve the cached language settings.
  # As part of the third step, the application makes attempts to acquire the language code associated with the current geographical location.
  # Finally, should all prior attempts prove unsuccessful, the application gracefully defaults to a fallback language.
  # In the event that no matching language is found within the "languageDictionary.json" file, the application will once again resort to utilizing the fallback language.
  # Even in the scenario where the fallback language yields no corresponding results within the "languageDictionary.json" file, the application will proceed to display the unprocessed keywords that were employed in the call to window.Language.use(KEYWORD).
  language:
    fallback: "en"

    # Languages that will be displayed in the language switcher
    supported:
      - "en"

  # To Control App's State (Offline, Under Development etc.)
  # appIsDown:
  #   title: "Under Development"
  #   explanation: "Long text that describes the 'title'"
  #   icon: "SVG Logo To Be Shown"

  # For External Color Configurations
  color:
    brand:
      hue: 230        # deg
      saturation: 13  # %
      lightness: 9    # %

  # App Icon Settings
  icon:
    favicon:
      sizes: "32x32"
      type: "image/png"
      dark: "favicon/favicon-32x32-dark.png"
      light: "favicon/favicon-32x32-light.png"

  # Enables All "print"s And "console.log"s
  debug: true


######### Pages
pages:
  home:
    enabled: true
    endpoints:
      - "/"
      - "/home"


  signUp:
    enabled: true
    authenticity_statuses:
      - "unauthenticated"

    endpoints:
      - "/signUp"


  logIn:
    enabled: true
    authenticity_statuses:
      - "unauthenticated"

    endpoints:
      - "/logIn"


  eMailConfirmation:
    enabled: true
    authenticity_statuses:
      - "unauthorized"

    endpoints:
      - "/eMailConfirmation"


  logOut:
    enabled: true
    authenticity_statuses:
      - "unauthorized"
      - "authorized"

    endpoints:
      - "/logOut"


  logOutInstant:
    enabled: true
    authenticity_statuses:
      - "unauthorized"
      - "authorized"

    endpoints:
      - "/logOutInstant"


######### Menu
menu:
  enabled: true
  menus:
    - page: "home"
    - page: "signUp"
    - page: "logIn"
    - page: "logOut"


######### Username
username:
  min_length: 6
  max_length: 50
  regEx: "^[a-zA-Z0-9'_-]+$"


######### Password
password:
  min_length: 6
  max_length: 50
  regEx: "^(?=.*[a-z])(?=.*[0-9])(?=.*[-!@#$%^&*_+])[-!@#$%^&*_+A-Za-z0-9]{6,}$"


######### Phone Number
phoneNumber:
  regEx: "^[+]{1,1}[0-9]{11,11}$"

